#!/usr/bin/bash
#SBATCH --partition="accelerated-h100"
#SBATCH --job-name="robust_dlw"
#SBATCH --time=48:00:00
#SBATCH --gres=gpu:1
#SBATCH --err=std.err
#SBATCH --output=std.out
#SBATCH --account="hk-project-p0026354"

module load devel/cuda/12.9

cd $SLURM_SUBMIT_DIR


export SLURM_NTASKS=${SLURM_NTASKS:=76}

# >>> mamba initialize >>>
# !! Contents within this block are managed by 'micromamba shell init' !!
export MAMBA_EXE='/hkfs/home/project/hk-project-bit2blo2_3/fy4301/.local/bin/micromamba';
export MAMBA_ROOT_PREFIX='/hkfs/home/project/hk-project-bit2blo2_3/fy4301/micromamba';
__mamba_setup="$("$MAMBA_EXE" shell hook --shell bash --root-prefix "$MAMBA_ROOT_PREFIX" 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__mamba_setup"
else
    alias micromamba="$MAMBA_EXE"  # Fallback on help from micromamba activate
fi
unset __mamba_setup
# <<< mamba initialize <<<

micromamba activate dlw_horeka

time python main_0.py > output.log

cd ..