import autograd
import tidy3d.web as web
import jax
import jax.numpy as jnp
import autograd.numpy as anp
from jax.debug import print as jprint

import numpy as np
from autograd.extend import primitive, defvjp

from problems.polarization_splitter.simulation.config_structure import ConfigSim
from problems.polarization_splitter.simulation.simulation import heat_simulation, make_sim_tidy
from utility.helper import logsumexp


def measure_mode_power_ag(rho):
    sim = make_sim_tidy(rho)
    sim_data_te = web.run(sim[0], task_name=f"pol_splitter_te_{ConfigSim.cur_it + 1}", folder_name="pol_splitter_dlw", verbose=False)
    sim_data_te.to_file(fname='problems/polarization_splitter/plots/progression/current_simulation_te.hdf5')
    output_amps_te = sim_data_te["Mode Monitor Horizontal"].amps
    leaked_output_amps_te = sim_data_te["Mode Monitor Vertical"].amps
    amp_te = output_amps_te.sel(direction='+', f=ConfigSim.freq0).values
    leaked_amp_te = leaked_output_amps_te.sel(direction='+', f=ConfigSim.freq0).values
    trans_te = np.sum(anp.abs(amp_te) ** 2) - 0.3*np.sum(anp.abs(leaked_amp_te) ** 2)

    sim_data_tm = web.run(sim[1], task_name=f"pol_splitter_tm_{ConfigSim.cur_it + 1}", folder_name="pol_splitter_dlw", verbose=False)
    sim_data_tm.to_file(fname='problems/polarization_splitter/plots/progression/current_simulation_tm.hdf5')
    output_amps_tm = sim_data_tm["Mode Monitor Vertical"].amps
    leaked_output_amps_tm = sim_data_te["Mode Monitor Horizontal"].amps
    amp_tm = output_amps_tm.sel(direction='+', f=ConfigSim.freq0).values
    leaked_amp_tm = leaked_output_amps_tm.sel(direction='+', f=ConfigSim.freq0).values
    trans_tm = np.sum(anp.abs(amp_tm) ** 2) - 0.3*np.sum(anp.abs(leaked_amp_tm) ** 2)

    ConfigSim.cur_it += 1

    # return anp.sum(anp.abs(trans_te)**(-ConfigSim.p) + anp.abs(trans_tm)**(-ConfigSim.p))**(-1/ConfigSim.p)
    return (trans_te + trans_tm) / 2


@jax.custom_vjp
def measure_mode_power(rho):
    return measure_mode_power_ag(rho)


def measure_mode_power_fwd(rho):
    x, dx = autograd.value_and_grad(measure_mode_power_ag)(anp.array(rho))

    return jnp.array(x), (jnp.array(x), jnp.array(dx))


def measure_mode_power_bwd(res, g):
    ans, dx = res
    return g * dx,


measure_mode_power.defvjp(measure_mode_power_fwd, measure_mode_power_bwd)


def objective_heat(rho):
    """
    Calculates the heat_eval generated by the material and the void of rho.
    :param rho: Density (design variable) of the problem [0, 1].
    :return: Tuple of material and void heat_eval.
    """
    T_mat, T_void, _ = heat_simulation(rho, ConfigSim.resize_factor)
    return T_mat, T_void


def objective_heat_f():
    return objective_heat


def objective_em_heat_f(init_values):
    def objective_softplus(rho):
        transmission = measure_mode_power(rho)
        v_heat_m, v_heat_v = objective_heat(rho)

        n_heat_m = (v_heat_m - init_values[0]) / init_values[0]
        n_heat_v = (v_heat_v - init_values[1]) / init_values[1]

        logs = {
            "transmission": transmission, "n_heat_m": n_heat_m, "n_heat_v": n_heat_v, "v_heat_m": v_heat_m,
            "v_heat_v": v_heat_v
        }



        print("====================")
        for name, log in logs.items():
            jprint("{name}:", name=name)
            jprint("    {log}", log=log)
        print("====================")

        objs = jnp.array([n_heat_m, n_heat_v])

        return transmission * (1 - jnp.linalg.norm(logsumexp(objs))), (transmission, 0)

    return objective_softplus


def objective_robust_em_heat_f(init_values):
    def objective_softplus(rho):
        transmission = measure_mode_power(rho)
        v_heat_m, v_heat_v = objective_heat(rho)

        n_heat_m = (v_heat_m - init_values[0]) / init_values[0]
        n_heat_v = (v_heat_v - init_values[1]) / init_values[1]

        objs = jnp.array([n_heat_m, n_heat_v])

        return transmission * (1 - jnp.linalg.norm(logsumexp(objs))), transmission

    def objective_robust_softplus(rhos):
        """
        Generates the robust objective function. By using the lp-norm (set by power), we approximate the maximum norm.
        The worst performing of the three input densities is optimized for.
        :param rhos: Densities (design variable) of the problem 3x[0, 1].
        :return: robust objective function, values for the EM-performances.
        """
        power = 19

        fom_eroded, trans_eroded = objective_softplus(rhos[0])
        fom_normal, trans_normal = objective_softplus(rhos[1])
        fom_dilated, trans_dilated = objective_softplus(rhos[2])

        fom_max = (fom_eroded ** power + fom_normal ** power + fom_dilated ** power) ** (1 / power)

        logs = {
            "trans_eroded": trans_eroded, "trans_normal": trans_normal, "trans_dilated": trans_dilated,
            "fom_eroded": fom_eroded, "fom_normal": fom_normal, "fom_dilated": fom_dilated,
            "fom_max": fom_max
        }

        print("====================")
        for name, log in logs.items():
            jprint("{name}:", name=name)
            jprint("    {log}", log=log)
        print("====================")

        return fom_max, (trans_eroded, trans_normal, trans_dilated)

    return objective_robust_softplus
