import autograd
import tidy3d.web as web
import jax
import jax.numpy as jnp
import autograd.numpy as anp
from jax.debug import print as jprint

import numpy as np
from autograd.extend import primitive, defvjp
from tidy3d import C_0

from problems.multiplexer.simulation.config_structure import ConfigSim
from problems.multiplexer.simulation.simulation import heat_simulation, make_sim_tidy
from utility.helper import softplus


def measure_mode_power_ag(rho):
    sim = make_sim_tidy(rho)
    task_name = "multiplexer"
    sim_data = web.run(sim, task_name=task_name, folder_name="multiplexer_dlw", verbose=False)
    trans_list = []
    trans_obj = []
    wavelengths = ConfigSim.eval_wvls
    for i in range(len(ConfigSim.eval_wvls)):
        output_amps = sim_data[f"Mode Monitor {wavelengths[i]}"].amps
        amp = output_amps.sel(direction='+', mode_index=0).values
        trans = anp.abs(amp[i]) ** 2
        trans_list.append(trans)
        leaked_trans = anp.sum(anp.abs(amp) ** 2) - anp.abs(amp[i]) ** 2
        avg_leaked_trans = leaked_trans / (len(ConfigSim.eval_wvls) - 1)
        trans_obj.append(trans - avg_leaked_trans)
    trans_obj = np.array(trans_obj)

    return anp.sum(trans_obj**(-ConfigSim.p))**(-1/ConfigSim.p)


@jax.custom_vjp
def measure_mode_power(rho):
    return measure_mode_power_ag(rho)


def measure_mode_power_fwd(rho):
    x, dx = autograd.value_and_grad(measure_mode_power_ag)(anp.array(rho))

    return jnp.array(x), (jnp.array(x), jnp.array(dx))


def measure_mode_power_bwd(res, g):
    ans, dx = res
    return g * dx,


measure_mode_power.defvjp(measure_mode_power_fwd, measure_mode_power_bwd)


def objective_heat(rho):
    """
    Calculates the heat_eval generated by the material and the void of rho.
    :param rho: Density (design variable) of the problem [0, 1].
    :return: Tuple of material and void heat_eval.
    """
    T_mat, T_void, _ = heat_simulation(rho, ConfigSim.resize_factor)
    return T_mat, T_void


def objective_heat_f():
    return objective_heat


def objective_em_heat_f(init_values):
    def objective_softplus(rho):
        fom_tr = measure_mode_power(rho)
        v_heat_m, v_heat_v = objective_heat(rho)

        n_heat_m = (v_heat_m - init_values[0]) / init_values[0]
        n_heat_v = (v_heat_v - init_values[1]) / init_values[1]

        logs = {
            "fom": fom_tr, "n_heat_m": n_heat_m, "n_heat_v": n_heat_v, "v_heat_m": v_heat_m,
            "v_heat_v": v_heat_v
        }

        print("====================")
        for name, log in logs.items():
            jprint("{name}:", name=name)
            jprint("    {log}", log=log)
        print("====================")

        objs = jnp.array([n_heat_m, n_heat_v])

        return fom_tr * (1 - jnp.linalg.norm(softplus(objs))), fom_tr

    return objective_softplus
