import autograd
import tidy3d.web as web
import jax
import jax.numpy as jnp
import autograd.numpy as anp
from jax.debug import print as jprint

import numpy as np
from autograd.extend import primitive, defvjp

from problems.mode_converter.simulation.config_structure import ConfigSimMode
from problems.mode_converter.simulation.simulation import heat_simulation, make_sim_tidy
from utility.helper import softplus


def measure_mode_power_ag(rho):
    sim = make_sim_tidy(rho)
    task_name = "mode_converter"
    sim_data = web.run(sim, task_name=task_name, folder_name="mode_converter_dlw", verbose=False)
    output_amps = sim_data["Mode Monitor"].amps
    amp = output_amps.sel(direction='+', f=ConfigSimMode.freq0, mode_index=3).values
    return anp.sum(anp.abs(amp) ** 2)


@jax.custom_vjp
def measure_mode_power(rho):
    return measure_mode_power_ag(rho)


def measure_mode_power_fwd(rho):
    x, dx = autograd.value_and_grad(measure_mode_power_ag)(anp.array(rho))

    return jnp.array(x), (jnp.array(x), jnp.array(dx))


def measure_mode_power_bwd(res, g):
    ans, dx = res
    return g * dx,


measure_mode_power.defvjp(measure_mode_power_fwd, measure_mode_power_bwd)


def objective_heat(rho):
    """
    Calculates the heat_eval generated by the material and the void of rho.
    :param rho: Density (design variable) of the problem [0, 1].
    :return: Tuple of material and void heat_eval.
    """
    T_mat, T_void, _ = heat_simulation(rho, ConfigSimMode.resize_factor)
    return T_mat, T_void


def objective_heat_f():
    return objective_heat


def objective_em_heat_f(init_values):
    def objective_softplus(rho):
        transmission = measure_mode_power(rho)
        v_heat_m, v_heat_v = objective_heat(rho)

        n_heat_m = (v_heat_m - init_values[0]) / init_values[0]
        n_heat_v = (v_heat_v - init_values[1]) / init_values[1]

        logs = {
            "n_heat_m": n_heat_m, "n_heat_v": n_heat_v, "transmission": transmission, "v_heat_m": v_heat_m,
            "v_heat_v": v_heat_v
        }

        print("====================")
        for name, log in logs.items():
            jprint("{name}:", name=name)
            jprint("    {log}", log=log)
        print("====================")

        objs = jnp.array([n_heat_m, n_heat_v])

        return transmission * (1 - jnp.linalg.norm(softplus(objs))), transmission

    return objective_softplus
