import jax.numpy as jnp
from jax.debug import print as jprint

from problems.metalens.simulation.config_structure import ConfigSim
from problems.metalens.simulation.simulation import em_simulation, heat_simulation
from utility.helper import softplus



def objective_em_f(currents, resolution, init_value):
    """
    Generates the pure EM-objective function.
    :param currents: Source currents of the simulation.
    :param resolution: Resolution of the simulation [px/um].
    :param init_value: Initial value of the problem to make a unitless comparison possible.
    :return: Pure EM-Objective function.
    """

    def objective_em(rho):
        """
        Pure EM-objective function, which evaluates the field enhancement at the focal spot.
        :param rho: Density (design variable) of the problem [0, 1].
        :return: Field enhancement at the focal spot of the x-component of E.
        """
        E, eps = em_simulation(rho, currents, resolution)
        focal_spot = E[0][
            E[0].shape[0] // 2, E[0].shape[1] // 2, int(jnp.ceil(ConfigSim.location_focal_spot * resolution))]
        return jnp.abs(focal_spot) / init_value, 0

    return objective_em


def objective_heat_f():
    """
    Generates the pure heat_eval-objective function.
    :return: Pure heat_eval-objective function
    """

    def objective_heat(rho, resolution):
        """
        Calculates the heat_eval generated by the material and the void of rho.
        :param rho: Density (design variable) of the problem [0, 1].
        :return: Tuple of material and void heat_eval.
        """
        T_mat, T_void, _ = heat_simulation(rho, ConfigSim.resize_factor, resolution)
        return T_mat, T_void

    return objective_heat


def objective_em_heat_f(currents, resolution, init_values):
    """
    Generates the (softmax) connectivity-objective function.
    :param currents: Source currents of the simulation.
    :param resolution: Resolution of the simulation [px/um].
    :param init_values: Initial value of the problem to make a unitless comparison possible.
                        Tuple of initial values for the EM, material heat_eval and void heat_eval simulation.
    :return: Connectivity-objective funtion.
    """

    def objective_em(rho):
        """
        Pure EM-objective function, which evaluates the field enhancement at the focal spot.
        :param rho: Density (design variable) of the problem [0, 1].
        :return: Field enhancement at the focal spot of the x-component of E.
        """
        E, eps = em_simulation(rho, currents, resolution)
        focal_spot = E[0][
            E[0].shape[0] // 2, E[0].shape[1] // 2, int(jnp.ceil(ConfigSim.location_focal_spot * resolution))]
        return jnp.abs(focal_spot) / init_values[0], eps

    def objective_heat(rho):
        """
        Calculates the heat_eval generated by the material and the void of rho.
        :param rho: Density (design variable) of the problem [0, 1].
        :return: Tuple of material and void heat_eval.
        """
        T_mat, T_void, _ = heat_simulation(rho, ConfigSim.resize_factor, resolution)
        return T_mat, T_void

    def objective_softplus(rho_0):
        """
        Generates the softplus objective function. Implements the virtual heat_eval method and filters it through a
        non-linear activation function. This is to make sure that once connectivity is reached, the optimizer disregards
        the contributions of the heat_eval solver.
        :param rho: Density (design variable) of the problem [0, 1].
        :return: Softplus objective function.
        """
        v_lens, eps = objective_em(rho_0)
        v_heat_m, v_heat_v = objective_heat(rho_0)

        n_lens = (ConfigSim.TARGET_EM - v_lens) / ConfigSim.TARGET_EM
        n_heat_m = (v_heat_m - init_values[1]) / init_values[1]
        n_heat_v = (v_heat_v - init_values[2]) / init_values[2]

        logs = {
            "n_lens": n_lens, "n_heat_m": n_heat_m, "n_heat_v": n_heat_v, "v_lens": v_lens, "v_heat_m": v_heat_m,
            "v_heat_v": v_heat_v
        }

        print("====================")
        for name, log in logs.items():
            jprint("{name}:", name=name)
            jprint("    {log}", log=log)
        print("====================")

        objs = jnp.array([n_heat_m, n_heat_v])

        return v_lens * (1 - jnp.linalg.norm(softplus(objs))), (v_lens, eps)

    return objective_softplus


def objective_robust_em_heat_f(currents, resolution, init_values):
    """
    Generates the (softmax) connectivity-objective function. A robust optimization is done by averaging over three
    different structures (eroded, normal and dialted).
    :param currents: Source currents of the simulation.
    :param resolution: Resolution of the simulation [px/um].
    :param init_values: Initial value of the problem to make a unitless comparison possible.
                        Tuple of initial values for the EM, material heat_eval and void heat_eval simulation.
    :return: Connectivity-objective funtion, value for the EM-performance.
    """

    def objective_em(rho):
        """"
        Pure EM-objective function, which evaluates the field enhancement at the focal spot.
        :param rho: Density (design variable) of the problem [0, 1].
        :return: Field enhancement at the focal spot of the x-component of E.
        """
        E, eps = em_simulation(rho, currents, resolution)
        focal_spot = E[0][
            E[0].shape[0] // 2, E[0].shape[1] // 2, int(jnp.ceil(ConfigSim.location_focal_spot * resolution))]
        return jnp.abs(focal_spot) / init_values[0]

    def objective_heat(rho):
        """
        Calculates the heat_eval generated by the material and the void of rho.
        :param rho: Density (design variable) of the problem [0, 1].
        :return: Tuple of material and void heat_eval.
        """
        T_mat, T_void, _ = heat_simulation(rho, ConfigSim.resize_factor)
        return T_mat, T_void

    def objective_softplus(rho):
        """
        Generates the softplus objective function. Implements the virtual heat_eval method and filters it through a
        non-linear activation function. This is to make sure that once connectivity is reached, the optimizer disregards
        the contributions of the heat_eval solver.
        :param rho: Density (design variable) of the problem [0, 1].
        :return: Softplus objective function, value for the EM-performance.
        """
        v_lens = objective_em(rho)
        v_heat_m, v_heat_v = objective_heat(rho)

        n_lens = (ConfigSim.TARGET_EM - v_lens) / ConfigSim.TARGET_EM
        n_heat_m = (v_heat_m - init_values[1]) / init_values[1]
        n_heat_v = (v_heat_v - init_values[2]) / init_values[2]

        objs = jnp.array([n_heat_m, n_heat_v])

        return v_lens * (1 - jnp.linalg.norm(softplus(objs))), v_lens

    def objective_robust_softplus(rhos):
        """
        Generates the robust objective function. By using the lp-norm (set by power), we approximate the maximum norm.
        The worst performing of the three input densities is optimized for.
        :param rhos: Densities (design variable) of the problem 3x[0, 1].
        :return: robust objective function, values for the EM-performances.
        """
        power = -20
        fom_eroded, v_lens_eroded = objective_softplus(rhos[0])
        fom_normal, v_lens_normal = objective_softplus(rhos[1])
        fom_dilated, v_lens_dilated = objective_softplus(rhos[2])

        fom_min = (fom_eroded ** power + fom_normal ** power + fom_dilated ** power) ** (1 / power)

        logs = {
            "v_lens_eroded": v_lens_eroded, "v_lens_normal": v_lens_normal, "v_lens_dilated": v_lens_dilated,
            "fom_eroded": fom_eroded, "fom_normal": fom_normal, "fom_dilated": fom_dilated,
            "fom_min": fom_min
        }

        print("====================")
        for name, log in logs.items():
            jprint("{name}:", name=name)
            jprint("    {log}", log=log)
        print("====================")

        return fom_min, (v_lens_eroded, v_lens_normal, v_lens_dilated)

    return objective_robust_softplus
